name: Build and Push Docker Image to Dockerhub
# THe Events to be done
on:
  push:
    branches:
      - master
# The jobs to be done in the GitHub
jobs:
  # jobs
  build-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    # Steps
    steps:
      # actions
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # checking out of the repository
      - name: Check out the repo
        uses: actions/checkout@v4

      #  Login into to the docker hub
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: elijahfaith/docker-ci-dockerhub
          tags: |
            type=raw,value=01

      - name: Build and push Docker image to Dockerhub
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
